part of tag_master.mustache_templates;

Map<String, String> texts = {
  "loginTitle": "Nejste úspěšně přihlášeni",
  "loginText": "Přihlašovací jméno",
  "passText": "Heslo",
  "submitText": "Odeslat",
  "loginSauce": "Jste přihlášen jako ",
  "loginName": "<span class='loginName'></span>",
  "logoutSauce": "Odhlásit",
  "buttonToOverviewSauce": "Přehled Tagů",
  "welcomeSauce": "Vítejte v TagMastru!",
  "acceptErrorSauce": "Beru na vědomí",
  "buttonToHomeSauce" : "Domů",
  "viewTagSauce" : "Zobraz Tag",
  "editTagSauce" : "Uprav Tag",
  "tagIdSauce" : "Id Tagu",
  "tagNameSauce" : "Jméno Tagu",
  "tagTypeSauce" : "Typ Tagu",
  "relationsFromSauce" : "Relations z tohoto Tagu",
  "relationsToSauce" : "Relations do tohoto Tagu",
  "relationIdSauce" : "Id",
  "relationStrengthSauce" : "Síla vazby",
  "notReadySauce" : "Tato funkcionalita ještě nebyla implementována",
  "addTagSauce" : "Vytvořit tag",
  "addRelationSauce" : "Další relation",
  "coreSauce" : "Základní Tag",
  "concreteSauce" : "Specifický Tag",
  "compositeSauce" : "Složený Tag",
  "commonSauce" : "Uživatelský Tag",
  "comparableSauce" : "Synonymum",
  "typ5" : "Základní Tag",
  "typ4" : "Specifický Tag",
  "typ3" : "Složený Tag",
  "typ2" : "Uživatelský Tag",
  "typ1" : "Synonymum",
  "ChangeTagTypeSauce" : "Změn typ Tagu",
  "backSauce" : "Zpět (v navigaci)",
  "submitChangesToTagSauce" : "Uložit Změny",
  "lostInNavigation" : "Ztratili jste se po cestě",
  "chooseTagTypeSauce" : "Vyberte typ Tagu",
  "chooseSynonymTargetSauce" : "Vyberte cíl synonyma",
  "tagName" : "Jméno tagu",
  "relogSauce" : "Změnit uživatele",
  "compoCompoRedirSauce": "Odkaz na kompozitní tag bude nahrazen odkazy na příslušné tagy vyšší úrovně",
  "chooseCompositeTargetSauce": "Vyberte součást tagu",
  "relTarget": "Cíl relace",
  "willBe": "bude"
};
